### ISSUE TITLE
组织原则细化

### ISSUE THREAD

**Issue by cmmei** [LirenCollege/LRC#3]
组织原则上，这样编排目录如何？

2011年
- LAT
  - XXX
- 授课文字稿
  - XXX
- 学员文章
  - XXX

---

2012年
- LAT
  - XXX
- 授课文字稿
  - XXX
- 学员文章
  - XXX

---

2013年
- 北京组
  - LAT
    - XXX
  - 授课文字稿
    - XXX
  - 学员文章
    - XXX

**或者**
2013年
- LAT
  - 北京组
    - XXX
  - 广州组
    - XXX

**Comment by tsai1993** [comment]
gitbook只能有一级目录，好像是这样。你可以去确定一下。

如果可以二级目录，第一种方式最好。

否则只能把年份合并到子目录中。变成2011年讲课文字稿，2011年学员文章。

**Comment by tsai1993** [comment]
LAT只有2013年才有。

**Comment by tsai1993** [comment]
突然发现这样更合理：

2013年
 - LAT
   - xx
   - xx
 - 北京授课文字稿
   - XXX
 - 广州授课文字稿
   - XXX
 - 学员文章

**Comment by tsai1993** [comment]
而且不同年份不一样 @cmmei

**Comment by cmmei** [comment]
嗯。可以。

**Comment by cmmei** [comment]
也就是说，授课文字按照年份——游学城市分开，学员文章只按照年份划分？

**Comment by tsai1993** [comment]
我觉得2013年可以这样，因为2013年学员文章好像不是很多。要是非要按照年份和城市来分，结构太细，难看。

**Comment by cmmei** [comment]
广州组的几乎每天都有简单记录。我刚放了三篇。

**Comment by tsai1993** [comment]
好吧，看了下，其他城市的学员文字加在一起不超过10篇，因此我觉得放一起没什么问题。

**Comment by tsai1993** [comment]
欧阳有十一封信，该怎么放？还是不放？

**Comment by cmmei** [comment]
要不把「学员记忆」这个名字改一下，授课之外的文字都放在这下面？

我建议先问一下欧阳，是否同意放上去公开吧。

**Comment by tsai1993** [comment]
嗯，好。看看改一个什么标题比较合适，要不就**记忆**？

**Comment by tsai1993** [comment]
感觉可以开一个专栏，与各城市平行，就叫欧阳的每周一信。真的是觉得13年欧阳太拼了，她应该有此殊荣。没有她，就不会有13年立大。

**Comment by cmmei** [comment]
也可以喔。放在「学员记忆」前面？

2016-03-22 1:07 GMT+08:00 tsai1993 <notifications@github.com>:
