### ISSUE TITLE
gitbook 没有更新到新的 github integration

### ISSUE THREAD

**Issue by cmmei** [LirenCollege/LRC#5]
gitbook 提示更新链接：

![Selection_001.png](https://i.loli.net/2017/11/01/59f9c2f08f530.png)

似乎需要创建者有权限操作：

![Selection_002.png](https://i.loli.net/2017/11/01/59f9c40ea373d.png)

**Comment by tsai1993** [comment]
不太知道是怎么回事，好像 gitbook 更新之后又加了一层权限，我把你添加为管理员了，你看下还有没有问题。我打开about页面没有那个提示，而且更新历史也是正常的。
